SELECT B.USER_ID, B.NICKNAME, 
concat(B.CITY," ",B.STREET_ADDRESS1," ",B.STREET_ADDRESS2) '전체주소',
concat(substring(B.TLNO,1,3),'-',substring(B.TLNO,4,4),'-',substring(B.TLNO,8)) '전화번호'
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B
ON A.WRITER_ID=B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(DISTINCT(A.BOARD_ID))>=3
ORDER BY B.USER_ID DESC;