-- 코드를 입력하세요
SELECT CAR_ID,ROUND(AVG(DATE),1) AVERAGE_DURATION
FROM (SELECT *, DATEDIFF(END_DATE,START_DATE)+1 DATE
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     ) CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING AVG(DATE)>=7
ORDER BY AVERAGE_DURATION DESC,CAR_ID DESC